app = 'postgres-new-dev'
primary_region = 'yyz'

[[service]]
internal_port = 5432
protocol = "tcp"
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0

[[service.ports]]
port = 5432

[[service.concurrency]]
type = "connections"
hard_limit = 25
soft_limit = 20

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1

[mounts]
source = "postgres_new_data"
destination = "/mnt/data"
